apiVersion: v1
kind: Namespace
metadata:
  name: validation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: validation
  labels:
    app: validate
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
        - name: webhook
          image: erdemstar/flask-admission-control:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 443
          volumeMounts:
            - name: certs-volume
              readOnly: true
              mountPath: "/etc/ssl/"
          imagePullPolicy: Always
      volumes:
        - name: certs-volume
          secret:
            secretName: admission-tls
---
apiVersion: v1
kind: Service
metadata:
  name: erdemstar
  namespace: validation
spec:
  selector:
    app: validate
  ports:
    - port: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: admission-tls
  namespace: validation
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ0akNDQTU2Z0F3SUJBZ0lVZitzS0JSazg4OXVlVnRZODdwVlVUWUNrVzh3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NURUxNQWtHQTFVRUJoTUNWRkl4RVRBUEJnTlZCQWdNQ0VsemRHRnVZblZzTVJFd0R3WURWUVFIREFoSgpjM1JoYm1KMWJERVZNQk1HQTFVRUNnd01SWEprWlcxemRHRnlVMlZqTVNVd0l3WURWUVFEREJ4RmNtUmxiWE4wCllYSWdRMjl1ZEhKdmJHeGxjaUJYWldKb2IyOXJNQjRYRFRJeU1URXdPVEV3TkRrMU5Wb1hEVEl6TVRFd09URXcKTkRrMU5Wb3djVEVMTUFrR0ExVUVCaE1DVkZJeEVUQVBCZ05WQkFnTUNFbHpkR0Z1WW5Wc01SRXdEd1lEVlFRSApEQWhKYzNSaGJtSjFiREVWTUJNR0ExVUVDZ3dNUlhKa1pXMXpkR0Z5VTJWak1TVXdJd1lEVlFRRERCeEZjbVJsCmJYTjBZWElnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlyTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEEKTUlJQ0NnS0NBZ0VBc3F0ZTJ5eVRjMldxd0hRRHkyZDI4L3JGYkFVZjRoWThycVg1M0tveFF0MTRrQUx5Sm95WgpxMFlhOUhyZDdzbGRYVDlmQUI3K1ZJRmd6cDFVYlVqZnpKVlQwSWNKL3p1eDd2OUhMRE12WE5mMTc1RXNsNzVQCmhJMXNoUWhUM0U1V2EwZEZTU25KN0ZjQ1FoYmxEa0YxZndpalloM1FncXdWM0hCSXh0QWhZMmY5N0ZMYkJ5ZlcKQlZDd08vM1dlY1NTTzQrck5zYzVlemhxL2tXZVhYdy9xUE9ZVTBoYjZFNEh5VG04RmJrd2ZOZzdhTHpBZWpSYwpGWEswV3d2T2FZRXpyUFI3UmlsOWV5WWR1cDY1QkNUOG55VFpoRWxlOXArVGRDR2NvcVR4T2tYRTliVjRqalN1CnFreWc0eHJHa213R05YN0I1eWJuUzk1R1hUM2xONHQrZXFZVVdHY1dZdytoSzBVcHl5UU16NmpDNW10VXB3TlAKVElSdWsrcDRGWmxTUXNNVk90UHkzZzd5aGpQWTFXRUQwM3V6azg1blY0SmVidWF5UDlic2J4cEFwcXdDdDlSOAptNThraFY5NjY0cVo0eVpneGFweENsV1VOa2x4OWpKR2xFS1lNTy9QcXlmdTlOZGp2UG5tdTJoOENzN1VPdlZCCjZNcjJMSVBRTkJCQ1ZFR2c4dXg1NXMyWDUvamh3SjRPb2ZyVXhiMHIwY3dxcUt4TmxQeWMvdk9zNWlWeFNqTkIKV2FsTUw2R0srbXQ5VVAxRDV1UWs3UE05RUlMcUVSSkV1T1RmMS9GbzJ5dGNucmpxTTlnYVpGblZBRWM5enpkNAptYW9IaEtKay93RTFaM1VOS0JZUDhjcEcrOCtRVldPcnh1Rk9mVjVYZm41VmtPOVNEaXRvd2NFQ0F3RUFBYU5HCk1FUXdJd1lEVlIwUkJCd3dHb0lZWlhKa1pXMXpkR0Z5TG5aaGJHbGtZWFJwYjI0dWMzWmpNQjBHQTFVZERnUVcKQkJTNU9OQjM4dFp3OHdUM2tGVk1VTVVYR0NiT0ZEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFMR2hsYWxZeApHVDVIUWUxM1dNcXJ4YmlrK1F4aTNDU0U4eElEYjBUaWF0dUlBeTYvODlSMVk5dnkwTGxjcXhRUGFpUnpndVY2CjZCRGl2KzdaVm9IcTVnTytoVlBmNUw2eU5yTVVIMTVFaXBaOEV4R0dWcDhUVXVsdUtudXhtUGJRaGRTN2lpU3kKcGhjUFRTYURXbjhZUEpGYU1Qd2x0UTJsbDVpbHAvOTFDZGJKbURld2FDQWprSWQvUTYvUXQ3R20rVXBXVCtaSQpLL1BDZ04wWW1aVTdYemw2aUduSU11MS9ScXNqWDdiSFdBR2JnMExJM3BBdTNrcGsrMGEwQkVyMEVIcmtJaHZSCm1QbUdNQ2laZGovZENFblp6M3dMMXkwM2I5bnZHNGZuS3RFaEtvWUd5ZVUxSlN3YUphYnBQODhUUEU3U1V5MVUKM016RXREQmZPdk5KWFZPeE9UZGdYdjFkRUhKRUlTMkxFQmI0WEI2M01scW51cGIyL2RtWlBRWlU2dVp1LzBCLwovNUdtUWFCaXNCc2R0WUhVbzZrWlZrK201aFBQOEU5cWpyaGhtd0dINjdDZitNTTBScEhuZmdCSVN3Ris0VkZvCmtaVldDVE5weWd0ZHY1bGxWOWhNMVlOOHJ4QU1Ga2cwUTlDSEU1d0JUSmlKZURNbVB6RUozRVQ3OXJTWXNDTWkKL0dLb1VYN0haZGFMTFkvSzFCeWlyNEEvSlJkQm9tMEF1Y1E3L1FxZFRFRDM4ZFY1Tk1lZzQzUzJseWxKZTh4WQpqc0QyY2g4R05JTUF3Y2RybzNVM2RwV0p6bnlCTzVkVWdRYTJBakx1VkxnUm5tWHdXZjhuNTNMbFZaQkp5K3hhCm5jRTAwOUljTXdRVElJL3gyTld0aUVsb0dYUnRqbnhmdWQwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Nzd2dna25BZ0VBQW9JQ0FRQ3lxMTdiTEpOelphckEKZEFQTFozYnorc1ZzQlIvaUZqeXVwZm5jcWpGQzNYaVFBdkltakptclJocjBldDN1eVYxZFAxOEFIdjVVZ1dETwpuVlJ0U04vTWxWUFFod24vTzdIdS8wY3NNeTljMS9YdmtTeVh2aytFald5RkNGUGNUbFpyUjBWSktjbnNWd0pDCkZ1VU9RWFYvQ0tOaUhkQ0NyQlhjY0VqRzBDRmpaLzNzVXRzSEo5WUZVTEE3L2RaNXhKSTdqNnMyeHpsN09HcisKUlo1ZGZEK284NWhUU0Z2b1RnZkpPYndWdVRCODJEdG92TUI2TkZ3VmNyUmJDODVwZ1RPczlIdEdLWDE3SmgyNgpucmtFSlB5ZkpObUVTVjcybjVOMElaeWlwUEU2UmNUMXRYaU9OSzZxVEtEakdzYVNiQVkxZnNIbkp1ZEwza1pkClBlVTNpMzU2cGhSWVp4WmpENkVyUlNuTEpBelBxTUxtYTFTbkEwOU1oRzZUNm5nVm1WSkN3eFU2MC9MZUR2S0cKTTlqVllRUFRlN09Uem1kWGdsNXU1ckkvMXV4dkdrQ21yQUszMUh5Ym55U0ZYM3JyaXBuakptREZxbkVLVlpRMgpTWEgyTWthVVFwZ3c3OCtySis3MDEyTzgrZWE3YUh3S3p0UTY5VUhveXZZc2c5QTBFRUpVUWFEeTdIbm16WmZuCitPSEFuZzZoK3RURnZTdlJ6Q3FvckUyVS9Keis4NnptSlhGS00wRlpxVXd2b1lyNmEzMVEvVVBtNUNUczh6MFEKZ3VvUkVrUzQ1Ti9YOFdqYksxeWV1T296MkJwa1dkVUFSejNQTjNpWnFnZUVvbVQvQVRWbmRRMG9GZy94eWtiNwp6NUJWWTZ2RzRVNTlYbGQrZmxXUTcxSU9LMmpCd1FJREFRQUJBb0lDQUFZcFNyZ2NMV21KVS80WEFocDlrdWlPCitVZmtWVmtpa3kwaXBCOHI3MDd5L0RsYklLYWJxcUR4WmZTUVdCN242c1JRYnlJOTcxOVNwdGY1TFBRbjB5L20KNW1FR2h4MjZIVVMwb091eFNDelhkYSt4UGV4dHI2aE9pRE4rT2dZYTNYZ05tU0lRd3RuWGxraFpLY1Q0Rk9rdwpqeEhQSFdXa01Zek1nblg0cjI0U0kvdUdUKzlMUEdJcWlpbEhjNkgzV1dPY2JMY1MzN1NVR1h4elFpYlBKaExaCmM2TkxsMy9IVVJWclhFVVRnY3lNV0dBZ1FqTDBvMGhLRUZZamJoYk5VYzdoRDI4Mzl3L01ITEpXenVLSnMveDQKOU5kUEFHdFl6V2p2ejhyOERTV0pTbVYrd0kyRzI0OGIzV0IzaCtsOHVDb1lHTyt6czc0MkNBOG5GMFIzRndGcwovOU8vY2gxM2dIZzJ6NTRiWGEydFI2UzJIMXJkSjlYQkJBdlFJNUdXWHhGSVdKSS83M3lvZmVocG1JQTAzNVY2CnFHMUZDa3Jqbjd4ak1ITkttSnExV2JsdWl1SEU1OURhbTQ4Z1R6OHFBWndvM3owbnRaRFdsZnNzWXRvcGZPZEIKQzNqRVJBMDkrRDVVaVdXcXB2MVMwaWEwc2t0SWd4WkM2d2EwYWgwNTkwR0U1andGS3dRNERIYlNmQkgwcmdrbQp6T1JnWXJOS2haUDJ0NFJQczYxZSt6cnJpbnZ5ajV0aEQ5S21RdURiWWg5VlpJMzdVS25YNjlMVjNNSEJBWStOCmdTR3RPL1lLNnN2bGdUanJNNDFHNGI4ZjBFYW5UYW1mdmp5QnFncGVpSG5FTGpZTzJnUnZLVjI5VWN0S1JNV1AKZno4eTJ6djJCaUVrRWcyUjlwbkJBb0lCQVFEYVhNa3NSQ2lNQWxocjhBb0ZZcFNpWCs4Z2cwYWZZcXFuK2NYeQo1dkdnOTByR1JRcERXZVREbWZPb3YyaWpocUkrVVQ3SjBFdThLK2p2UVVJL3Z3b3JySy9HOTNQOEFIYTI2RnVICjl4bFNXUFZuRTJtU05XVVl4VEZ1eEYzNi9IbzlSRFNDQ25Sa0o5U3ZlNE14OExEanR1MysxeUZYRUpxSEpucXMKUHlFSjk0UlI0RFFMenA4UHJyQzdONUxlZkRGQko1TDRtWFVTc0JTbW1yMnRDemxzLzNPbTgrQU9QckhldHJGTApzZEtPL01xNW91b0h3RVBUcFZoMFlMZmdCS0ozM1V6ZnRxdUpqMzdhSlpiUmp3OGpBY0Ftd01YSVBOU3M3cmpkCkRZcEVvR0hxeitWT1o0VzNNcFlxTE1tOU1SNzMxeE10dXZSRTdwYmgyMHRVVUlYMUFvSUJBUURSZHlLUm10anEKUVJDTkg5TG4zVS84Uk5ZRUlJNk1aYnVYWWE0NnNnVmtra2tvamI1VHI0KzVuRzlDREJTdkEzN3JLRmdGLzdndgo3TDY1dWFpRUtMY3NtbkliWVZGMmI3WVRyNEhCODFlOTFHU2hkMFNuR29IZzlyRTNWV2V5TDBqc0dWVFAvL0llCk9xR25RaVI2M0RlZmorMWVKZUdSc01QWDFBcTJaZGdjNUhoNG5jREI5N0pUV3hJMHVuQzR4c3JNQmFWQnV5MTIKeG1yQnl2Y2R1dUhGSXdtRHhKdmQ3Sy9mRUZES0h3aFhhRFBhK2QyY3FQSjFmZ2lFWTFUck1SSjBMcFlnNm5PNQpSR3hvMWdKNHErYlYrUlZiNllBeGs1QzVKZWhUeDE0RVRXWDV0Q3dCTVZhbE9lYnRlL0dYRVJxRDRaWmE3Vk5CCnhqaklyelpnMFNFZEFvSUJBRXNhc01LOTZxaEZRajVWd0V5YjNIMkF1NUdXTlZzcXA0SEE0Zm1xdng3YkQyZmsKWlNSSExleXM3ZVp6ZHowUFdJeFFpMlVFZEpnVERqb0VXeEhyMWtheFRZQUVxbXJaaWZ0ZExlWTA4Z3VsdHpvdApyaGp3cm9YM2hRb1JGalgyVXVEeHJaR3dvTm0xN1d3eDhpemlHU1VwVFBCaTgvK3JJVXNzeS9La2YrdWFxM014Cnh4VHNpejdzbWJLNjZaUUdhVFo4c3dzNFZORUpxUUNvcG1aM1B0Z2pnSmJDdUtTTm9jWDFWa092dExramIyS3MKQ3d5QmI1TERBd3A4SGFJNlZkc2VUWXVBbTcxamtvRGJmdVV5N0VUaEhFTDMrTTduUlVyNWpMSFRMMlJ0T1dCMwpBdXFWcHFNZERoTVJkbzNROEZMVU1hOS81dll5amNpL0VVaTlyV1VDZ2dFQVFxcENERWxXSkNnVkZuVThjS01WCkk5cmNxbSthTHNEcUZXSDNTNk1BNkdOT2VXT3pZWHNNcVN4S2xLQzNySVBXVHcyR0JsSyswakhzK2J0SEVOak0KZzV1Y0dXNjl1STRSU3U2ZXc1V3BKVGVGMTRYWUNiNzcreGRJaTYzWTFQTUxxR2pmZjF1Y09WYTd3RG5pMWw5awpMSnBvRjREQzY5VndYeTZUUWozanJENWl3VENqK3BmVTM0YXFvckY3MHJNaU5CRFA2YjJpMkp5SnVhZlpRbE1LCksrM2N4MTA1cGtZQUsyUkw4aWd5Ulc5YW9hVElqV1dQMVNrSm1PanNTL1pRUXozWWRoMW9PMXkxakNBZ3BUdEEKdW5VT0FUU3RvaG12QTk0MnRRTk12dDNMU00rNCthQTBUVjNDUzI4WkV0VlV0UWlGQytkZ2loeUdVZ2pCcThxagpXUUtDQVFBTXdoejBPdkE1WVplc1B3ZFJidnhoZ0RNd1NNMzdZOTE5ZUZKUzBJNCtoR0ErNXRHdkNxVVNQSkMrCmQyZWRTSHNPNkgwNFBuUWRxdFJmK3MyMGxyS2dVZVQyWHdCN2Fvd1lnUmhkMjhMSHkxaFFqTXc5cnpzM2wyNkEKaTgweXRUR3hzNTdRb1NleVVhSFp6YXlTVTJ3dW92UkhGMkpYQnBKNGdXa01PeDM4Qy9GU3VTL2NZak5OUjV1dApaZDJSdXh0eitFMUp1aHNxTFArTGlGcVJkTjdaTjE5SG5kTWtxZ0RVQmlac2RHZDRHYnR0c09BZGlzeG1QSFI5Cnp4akg0L0NIclE3US8rZndGMzZBeUQ2bzlqNWt5UmxCVTNJcU52aE1yMUcxVnNGeG5aTDA5ZCtPcFU5eU9YYnAKSkJoOU00ckNITEl3M2IyMFJzRWxNZjNkSmNYSQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==